### PR TITLE
prevent a click to be triggered after binding

### PR DESCRIPTION
**Pull request by mjntan35**

### CODE REVIEW

**Comment by ndelvalle** [comment]
Thanks for the contribution @mjntan35 I will test and release a new version this weekend 👍

**Comment by Alex-Sokolov** [comment]
@ndelvalle any news about update? :)

**Comment by ndelvalle** [comment]
Published under v-click-outside@2.1.0-0 or using `next` tag. I need to update some test from changes merged to master in a previous PR before creating a release.

**Comment by ndelvalle** [comment]
Deployed `v-click-outside@2.1.0-1`

**Pull request merged**
