### PR TITLE
Add typescript support for clickOutside directive

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by deefour** [comment]
I don't think a [shorthand ambient module](https://www.typescriptlang.org/docs/handbook/modules.html#shorthand-ambient-modules) is correct way for a library to implement Typescript support. I'd prefer to see TypeScript error out when importing this module, requiring I acknowledge it is missing proper type declarations by adding the ambient module to my own `.d.ts` file.

**Comment by ndelvalle** [comment]
@astagi this is a bit hacky, it make it looks like we have TS but we actually don't 😅

**Comment by astagi** [comment]
@deefour I know this, you're absolutely right! This is not the correct way to implement TS, this is just a hacky fix to support TS rapidly, avoiding errors when you import this module. Let me know if you want to merge this PR and release a new version with this fix or if you prefer waiting for a better TS support, in the latter case I would convert this PR to draft and start working on TS support

**Comment by ndelvalle** [comment]
@astagi I prefer to have a better TS support for sure 🙂

**Comment by astagi** [comment]
Ok @ndelvalle this PR switches now to WIP 😉

**Pull request closed without merging**
