### PR TITLE
Use Event.composedPath() to detect location of event.target, Fixes #112

### LINKED ISSUE #112: El.contains does not work if element no longer exists in DOM
By the time the event bubbles, if the event.target is no longer in the DOM, el.contains will return false which incorrectly registers as an 'outside' click. This limits the usefulness of this package, fixes include:

- Add Event.stopPropagation on every single element that is removed from the DOM after the event bubbles.
- Use Event.composedPath() / Event.path to correctly detect event.target location at the time of the event.

### PR DESCRIPTION
**Pull request by aariacarterweir**
Fixes #112

### CODE REVIEW

**Comment by ndelvalle** [comment]
@aariacarterweir thanks for the pull request, I'm doing a bit of research about this new dependency. I don't fully like this polyfill, it does not use the DOM API real method name and I'm not sure where the implementation is coming from, but looking around I can't find a better polyfill for now.

**Comment by aariacarterweir** [comment]
Totally agree but I essentially came to the same conclusion :(

**Comment by aariacarterweir** [comment]
The solution is effective, however as @ndelvalle said it’s not been implemented in an ideal way. However I couldn’t find anything else that does the job, so I’ve been using this in my projects for now.

**Comment by ndelvalle** [comment]
So, compose path is supported in almost every browser except edge, more info [here](https://caniuse.com/#search=composedPath). What do you think about using it when available, and if not fall back to the old behavior? At least is a better implementation than the current one.

**Comment by germain-receeve** [comment]
This PR solved my issue as well and worked flawlessly on Edge contrary to what's stated (maybe the polyfill used handles a fallback for Edge/IE11 now?)
Anyway, could we please consider merging it for a new release?
This would be incredibly useful!

**Comment by germain-receeve** [comment]
> So, compose path is supported in almost every browser except edge, more info [here](https://caniuse.com/#search=composedPath). What do you think about using it when available, and if not fall back to the old behavior? At least is a better implementation than the current one.

Also I agree with this, maybe something along the lines:
```
  const checkMethod = event.propagationPath
    ? event.propagationPath().indexOf(el) < 0
    : !el.contains(event.target);

  const isClickOutside = event.target !== el && checkMethod;
```

**Comment by ndelvalle** [comment]
@germain-receeve makes sense to me, do you mind creating a PR? :)

**Comment by germain-receeve** [comment]
> @germain-receeve makes sense to me, do you mind creating a PR? :)

https://github.com/ndelvalle/v-click-outside/pull/170

**Comment by ndelvalle** [comment]
Closing in favor of https://github.com/ndelvalle/v-click-outside/pull/170

**Pull request closed without merging**
